spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: create-drop #update create-update validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    database: mysql
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/test2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: testuser
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver